### ISSUE TITLE
 'Monster' object has no attribute 'joining_cutoff'

### ISSUE THREAD

**Issue by rsanchezgarc** [matteoferla/Fragmenstein#14]
It seems that during refactoring, the joining_cutoff argument for place was never included and thus, victor.place() using full mode will crash if fragments needed to be joined

  File 'Fragmenstein/fragmenstein/monster/_join_neighboring.py", line 83, in _join_atoms
    if distance > self.joining_cutoff:
AttributeError: 'Monster' object has no attribute 'joining_cutoff'

**Comment by matteoferla** [comment]
Thanks. I'll declare `self.joining_cutoff` in the constructor.

However, the problem may be worse... The merging of the suggested hit prior to placement is pretty much an abandoned strategy —the default is no prior merging. The reason it is was even a thing was because the Postera Covid compound suggests had many red herrings, which should not really be the case for other projects. So the code for full and partial may have rotted away. They were not outright deleted because some Postera Covid compounds have 10+ suggestions, which the factorial time for no prior merging mode cannot handle (2 hours or something).
