### ISSUE TITLE
main branch tests failing

### ISSUE THREAD

**Issue by rsanchezgarc** [matteoferla/Fragmenstein#18]
The following tests are currently failing in the master branch under my setup

MProPlaceTester.test_easy
MProPlaceTester.test_nasty
MProPlaceTester.test_pentachromatic

VictorCombineTests.test_covalent (this by a very small margin: Exception: 1.066215269070932 not less than 1 : RMSD great that one (1.066215269070932))

**Comment by matteoferla** [comment]
The MProPlaceTester tests that fail were due to user submitting something tricky. The tests are specific to the issue that is the MPro submission dataset, so not broadly applicable.
`test_easy` renamed to `test_red_herring` as it is a misnomer —it is an easy call for a human— but added a note in documentation for it as it is curious. In reality disallowing rejected molecules will give the correct answer, however, this three way combination is an interesting challenge.

**Comment by matteoferla** [comment]
Also, the test file is over the 250 line max PEP thinggy, but I don't think it needs fixing —if anything, I can add more lines 😆
