### ISSUE TITLE
Bond angle errors using RDKit minimisation

### ISSUE THREAD

**Issue by kate-fie** [matteoferla/Fragmenstein#49]
Hello!

Versions:
```
Python 3.9.18 (main, Sep 11 2023, 08:25:10) 
[Clang 14.0.6 ]
on Darwin arm64
with Fragmenstein 0.14.6 and PyRosetta  2023.21+release.9b3660a8932
```

I have seen a few examples where using `Wictor` a compound is successfully minimised with a negative ΔΔG value but upon further investigation violates proper internal bond angles. The below example is the` minimised.mol` and has a -8.119004 ΔΔG. 
![image](https://github.com/matteoferla/Fragmenstein/assets/77400066/ab64d317-04bb-4499-b872-63d68fc1afdd)

Code used to run placement:
```
from fragmenstein import Laboratory, Wictor
from fragmenstein.laboratory.validator import place_input_validator

Wictor.monster_throw_on_discard = True  # stop this merger if a fragment cannot be used.
Wictor.monster_joining_cutoff = 5  # Å
Wictor.quick_reanimation = False  # for the impatient
Wictor.error_to_catch = Exception  # stop the whole laboratory otherwise
Wictor.enable_stdout(logging.CRITICAL)
Laboratory.Victor = Wictor

lab = Laboratory(pdbblock=pdbblock, covalent_resi=None, run_plip=False)
placements: pd.DataFrame = lab.place(place_input_validator(input_df), n_cores=4, timeout=500)
```

I've attached Fragmenstein output dirs with these examples and the output `placements.csv`. I have noticed they are all using the same fragment inspiration combination, so could it be coming from the restrictive atom mapping? Is there a check performed for intramolecular validity?

[bond_angle_errors.zip](https://github.com/matteoferla/Fragmenstein/files/14572501/bond_angle_errors.zip)

Thank you for your insight!

**Comment by matteoferla** [comment]
Oh no! Not one of those... I recognise that C shaped monstrosity: it's a 6-membered ring mapped onto a 5-membered ring. Whereas in the combination route the rings are collapsed, they are not in the placement for historical reasons —I did some tests and it was inconclusive/problematic.

For a separate sanity check for compounds, CSD Mogul ([example](https://github.com/matteoferla/Fragment-hit-follow-up-chemistry/blob/main/fragment_elaboration_scripts/mogul_zscore.py)) could be an option. I was thinking of a nice pipeline where I repeat any bad placements with the high Z-score atoms from the parent hit banned in the custom_map.

For now:
* I'll check now if the inner workings settings (`ff_max_displacement`, `ff_constraint`) are okay in Wictor
* In the PyRosetta implementation the constraints are to the ring's centre of mass, but not in the RDKit implementation —fix required.
* Also I need to double check with these if the ideal conformer is okay. The  ∆G_bind is calculated against a single ideal compound. However, it should fail minimisation i.e. ∆G_bind = NaN let alone have a positive one.

But I won't get to it before Friday

**Comment by matteoferla** [comment]
I found that this was a major issue beyond `Wictor`, so I prioritised it.
The issue dominoed down from a recent fix for PDB atom names (which was creating a copy).
As an extra. As the 5 to 6 membered ring mapping could be a pointless strain I have lowered the harmonic constrain on ring atoms, so RDKit behaves less strictly with ring atoms.

## Second bug
In the above snippet shared, the code on my system was running Victor. This correctly carps:
```python
from unittest.mock import Mock
lab = Laboratory(pdbblock=pdb_block, covalent_resi=None, run_plip=False)
lab.Victor = Mock
placements: pd.DataFrame = lab.place(place_input_validator(input_df), n_cores=4, timeout=500)
```
But this wasn't
```python
Laboratory.Victor = Mock
lab = Laboratory(pdbblock=pdb_block, covalent_resi=None, run_plip=False)
placements: pd.DataFrame = lab.place(place_input_validator(input_df), n_cores=4, timeout=500)
```
The odd thing was it was the lab instance in the main process had the right attribute, but in the Pebble subprocesses it had the original. It is "patched" (I set the instance attribute to match the class attribute).

## Mapping
`x0310A`, `x0732A` placement is a curious one as the ring atoms superpose problematically. It gives a good energy with Victor, okay RMSD but with four unconstrained atoms.
The requested compound is a benzene with a pair of meta amides. The primary parent hit is the pyrazole having a much larger arm (nitrile side). Due to the atom overlaps, the alpha-ketol arm is mapped as on the methyl group of the pyrazole not the intended arm.
![image](https://github.com/matteoferla/Fragmenstein/assets/11302983/7af83e5c-3dcb-4695-bb10-0df58f2d88ba)

There are three improvements that can be done.

* the expansion strategy is used on decomposed hits with modification to the error raising for not contributing hits if all synthons are useless. This would make scaffold hopping more efficient, but will slow things down
* the rings are collapsed like they are for combine route. And the expansion mapping strategy is used twice, once collapsed and once expanded with the restrictions from the previous. Would benzene to bicyclopentane (not propallane) work?

## Code for my reference

```python
from typing import List
from rdkit import Chem
from fragmenstein import Wictor, Monster, Victor, Igor, demo, Walton
from IPython.display import display
from ipywidgets import Output
from pathlib import Path
import json

chembase_code = 'IGUPJTYXYZPOEC-UHFFFAOYSA-N-4Sratv-base-A'
folder = (Path('~/Downloads/bond_angle_errors/') / chembase_code).expanduser()
x0310A = Chem.MolFromMolFile((folder / 'A71EV2A-x0310A.mol').as_posix())
x0732A = Chem.MolFromMolFile((folder / 'A71EV2A-x0732A.mol').as_posix())
pdb_block='\n'.join([l for l in (folder / f'{chembase_code}.holo_minimised.pdb').read_text().split('\n') if 'LIG' not in l])
derivative_smiles = json.loads(Path(folder / f'{chembase_code}.monster.json').read_text())['smiles']

Igor.init_pyrosetta()

vicky = Victor([x0310A, x0732A], pdb_block=pdb_block)
vicky.place(derivative_smiles, long_name='test')
vicky.make_pse()
```

**Comment by kate-fie** [comment]
Thank you Matteo for the detailed response and design tips!
